FROM envoyproxy/envoy:v1.22.0
RUN apt-get update && apt-get install -y software-properties-common
COPY ./envoy/envoy-config.yaml /etc/envoy.yaml

RUN chmod go+r /etc/envoy.yaml

EXPOSE 8001
EXPOSE 30000

CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "--log-level", "info", "--service-node", "${HOSTNAME}", "--service-cluster", "client"]
