static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 30000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: balancer-cluster
          http_filters:
            - name: envoy.router
              typed_config: { }
  clusters:
  - name: balancer-cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: balancer-cluster
      endpoints:
        - endpoint:
            address:
              socket_address:
                address: balancer
                port_value: 11002
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
